POST http://localhost:9090/api/v1/documents/create HTTP/1.1
Content-Type: application/json

{
    "title" : "first title",
    "contents" : "first contents"
}
###
POST http://localhost:9090/api/v1/documents/create HTTP/1.1
Content-Type: application/json

{
    "title" : "second title",
    "contents" : "second contents"
}
###
POST http://localhost:9090/api/v1/documents/create HTTP/1.1
Content-Type: application/json

{
    "title" : "third title",
    "contents" : "third contents"
}
###
PUT http://localhost:9090/api/v1/documents/JBcaCXYBowxxPQTRzmD4 HTTP/1.1
Content-Type: application/json

{
    "doc": {
        "title" : "first title changed 1",
        "garbageProperty" : "this should be not showing",
        "contents" : "first contents changed 1"
    }
}
###
POST http://localhost:9090/api/v1/documents/create HTTP/1.1

{
    "title" : "i love 구름이",
    "contents" : "구름이 is imp"
}
###
GET  http://localhost:9090/api/v1/documents/get/IxcVCXYBowxxPQTRtmBi HTTP/1.1

###
GET http://localhost:9090/api/v1/documents/search/seconds
###
DELETE http://localhost:9090/api/v1/documents/ajwS9HUBnu6QCXvpCIv-




https://stackoverflow.com/questions/32643815/json-omitempty-with-time-time-field